# Generated by Django 2.1.1 on 2018-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstractorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=32, verbose_name='パスワード')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('constractor', models.CharField(max_length=256, verbose_name='会社名')),
                ('representative', models.CharField(max_length=256, verbose_name='代表者\u3000職氏名')),
                ('address', models.CharField(max_length=512, verbose_name='所在地')),
                ('tel', models.CharField(max_length=16, verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='ユーザー名')),
                ('client', models.CharField(max_length=256, verbose_name='申請人')),
                ('address', models.CharField(max_length=512, verbose_name='申請人 住所')),
                ('tel', models.CharField(max_length=16, verbose_name='申請人 電話番号')),
                ('constract', models.IntegerField(default=0, verbose_name='工事種別（0:新設、1:改造、2:増設）')),
                ('place', models.CharField(max_length=512, verbose_name='施工場所')),
                ('start', models.DateField(verbose_name='工事開始日')),
                ('end', models.DateField(verbose_name='工事完了日')),
            ],
        ),
    ]
