# Generated by Django 2.1.1 on 2018-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='condition',
            field=models.IntegerField(default=0, verbose_name='状態（0:申請中、1:訂正中、2:許可済、3:完了済）'),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='findings',
            field=models.TextField(blank=True, verbose_name='指摘事項'),
        ),
    ]
