# Generated by Django 2.1.1 on 2018-12-15 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0002_auto_20181215_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constractorinfo',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='condition',
            field=models.IntegerField(default=0, verbose_name='状態（0:申請中、1:要訂正、2:許可済、3:完了済）'),
        ),
    ]
