# Generated by Django 2.1.1 on 2018-12-15 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0003_auto_20181215_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提出日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='constract',
            field=models.CharField(choices=[('0', '新設'), ('1', '改造'), ('2', '増設')], max_length=1, verbose_name='工事種別'),
        ),
    ]
